# Pre-commit configuration
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
  # Built-in pre-commit hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-xml
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-symlinks
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: detect-private-key
      # - id: detect-aws-credentials

  # Gitleaks for comprehensive secret detection
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.27.2
    hooks:
      - id: gitleaks

  # Additional security scanning with truffleHog (optional - can be commented out if too slow)
  # - repo: https://github.com/trufflesecurity/trufflehog
  #   rev: v3.63.2
  #   hooks:
  #     - id: trufflehog
  #       name: TruffleHog
  #       description: Detect secrets with TruffleHog
  #       entry: trufflehog
  #       language: golang
  #       stages: [commit]
  #       args:
  #         - --json
  #         - filesystem
  #         - --directory=.
  #         - --only-verified

  # Code quality hooks (add based on your tech stack)
  # Uncomment and configure based on your project's needs:

  # For JavaScript/TypeScript projects:
  # - repo: https://github.com/pre-commit/mirrors-eslint
  #   rev: v8.56.0
  #   hooks:
  #     - id: eslint
  #       files: \.(js|ts|jsx|tsx)$
  #       types: [file]
  #       additional_dependencies:
  #         - eslint@8.56.0

  # For Python projects:
  # - repo: https://github.com/psf/black
  #   rev: 23.12.1
  #   hooks:
  #     - id: black
  #       language_version: python3

  # - repo: https://github.com/pycqa/flake8
  #   rev: 6.1.0
  #   hooks:
  #     - id: flake8

  # For general file formatting:
  # - repo: https://github.com/pre-commit/mirrors-prettier
  #   rev: v3.1.0
  #   hooks:
  #     - id: prettier
  #       files: \.(js|ts|jsx|tsx|json|css|scss|html|yaml|yml|md)$
